version = 0.1
[default.deploy.parameters]
stack_name = "sam-linkedin-project1"
resolve_s3 = true
s3_prefix = "sam-linkedin-project1"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
